kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: studybuddy
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-pv